#PRODUTOS

CREATE TABLE IF NOT EXISTS db_mateus.produtos (
  id  BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  codigo_barras VARCHAR(45) NOT NULL UNIQUE,
  descricao VARCHAR(45) NOT NULL UNIQUE,
  preco_unitario DECIMAL(7,2) NOT NULL
  )
ENGINE = InnoDB 
DEFAULT CHARACTER SET = utf8;

#FORMAS_PAGAMENTOS
# TALVES FOSSE INTERESSANTE A TROCA DESTA TABELA POR UM ENUM EM UMA CLASSE ESPECÍFICA

CREATE TABLE IF NOT EXISTS db_mateus.formas_pagamentos(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
descricao varchar(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;


#CLIENTES

CREATE TABLE IF NOT EXISTS db_mateus.clientes(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;


#USUARIOS

CREATE TABLE IF NOT EXISTS db_mateus.usuarios(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;